name: SkullSecurity
title: SkullSecurity Blog
email: your-email@example.com
description: Adventures In Security
url: "https://www.skullsecurity.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/skullsecurity.jpg

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image:
        path: /assets/skullsecurity.jpg
        height: 100
        width: 100

paginate: 20
excerpt_separator: '<!--more-->'

include:
  - '_pages/'
  - '_wiki/'

exclude:
  - 'hooks/'
  - '*.sh'
  - 'README.md'
  - 'TODO.md'
  - 'templates/'
  - 'tooling/'

# Mastodon comment settings
comments:
  host: infosec.exchange
  username: skullsecurity

collections:
  authors:
    output: true
  categories:
    output: true
  widgets:
    output: true
  posts:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

feed:
  path: /feed
